# http://travis-ci.org/#!/MongoEngine/mongoengine
language: python
services: mongodb
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
  - PYMONGO=dev
  - PYMONGO=2.4.1
  - PYMONGO=2.3
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then cp /usr/lib/*/libz.so $VIRTUAL_ENV/lib/; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install pillow --use-mirrors ; true; fi
    - if [[ $PYMONGO == 'dev' ]]; then pip install https://github.com/mongodb/mongo-python-driver/tarball/master; true; fi
    - if [[ $PYMONGO != 'dev' ]]; then pip install pymongo==$PYMONGO --use-mirrors; true; fi
    - python setup.py install
script:
    - python setup.py test
notifications:
  irc: "irc.freenode.org#mongoengine"
branches:
  only:
    - master
    - "0.8"
# # Get development headers for PIL
# before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get build-dep -qq python-imaging
#  - sudo apt-get install libjpeg-dev
